<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AssemblyName>SwarmUI-WildcardImporter</AssemblyName>
    </PropertyGroup>
    <Import Project="../../SwarmUI.extension.props" />
    <PropertyGroup>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Mages" Version="3.0.1" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>
</Project>